### ISSUE TITLE
Issue pro srouba

### ISSUE THREAD

**Issue by RadeksGalaxy** [RadeksGalaxy/WAC4a#5]
Udelej aby mi vyskakovaly lepsi alerty pri spatne registraci. :>
:} 
🥇

**Comment by YepShroub** [comment]
ok lasko ❤️

**Comment by RadeksGalaxy** [comment]
cekej jeste nez zacnes 
ja to updatnu code

**Comment by YepShroub** [comment]
potrebuju permise na push sefe

**Comment by RadeksGalaxy** [comment]
jak to udelam

**Comment by YepShroub** [comment]
settings -> collaborators -> add

**Comment by YepShroub** [comment]
Mas to tam, vubec jsem to neotestoval, tak snad dobry.

**Comment by RadeksGalaxy** [comment]
ok
